name: Check and Print Condition

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js (required for GitHub API requests)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check if the pull request was merged
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "Pull request has been merged into main"
            echo "MERGED_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          else
            echo "Pull request was not merged."
            exit 1

      - name: Get the merged branch name
        if: ${{ env.MERGED_BRANCH }}
        run: echo "BRANCH_TEST=${{ env.MERGED_BRANCH }}" >> $GITHUB_ENV

      - name: List all branches in other repositories and check if merged into main
        if: ${{ env.MERGED_BRANCH }}
        id: list_branches
        run: |
          ORG_NAME="RandomOrganizationTest"
          BRANCH_TEST="${{ env.MERGED_BRANCH }}"
          BASE_BRANCH="main"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"

          # Get a list of repositories
          repos=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/orgs/$ORG_NAME/repos?per_page=100" | jq -r '.[].name')

          branch_merged=true
          merged_repo_names=""

          for repo in $repos; do
            response=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$ORG_NAME/$repo/compare/$BASE_BRANCH...$BRANCH_TEST" | jq -r '.status')

            if [[ "$response" == "identical" || "$response" == "behind" ]]; then
              echo "Branch $BRANCH_TEST has already been merged into $BASE_BRANCH in repository $repo"
              merged_repo_names="$merged_repo_names,$repo"
            else
              echo "Branch $BRANCH_TEST is not merged into $BASE_BRANCH in repository $repo"
              branch_merged=false
            fi
          done

          # Remove leading comma from the merged_repo_names
          merged_repo_names=${merged_repo_names#,}

          if [[ "$branch_merged" == true ]]; then
            echo "BRANCH_MERGED=true" >> $GITHUB_ENV
            echo "MERGED_REPO_NAMES=$merged_repo_names" >> $GITHUB_ENV
          else
            echo "BRANCH_MERGED=false" >> $GITHUB_ENV

      - name: Print "test" if no branches exist in other repositories
        if: ${{ env.BRANCH_MERGED == 'false' }}
        run: echo "test"

      - name: Run conan install if no branches exist in other repositories
        if: ${{ env.BRANCH_MERGED == 'false' }}
        run: |
          echo "Running conan install..."
          conan install --build=update --build=cascade --build=missing --build="${{ env.MERGED_REPO_NAMES }}"
